# Generated by Django 4.0.3 on 2022-04-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
